version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "npm"
    directory: "/src"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/src/apps/ontodia"
    schedule:
      interval: "monthly"

  - package-ecosystem: "npm"
    directory: "/src/apps/www"
    schedule:
      interval: "weekly"
